services:
  postgres:
    image: postgres:16-alpine
    container_name: Shuttlez-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: Shuttlez
      POSTGRES_USER: Shuttlez
      POSTGRES_PASSWORD: Shuttlez123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: Shuttlez-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
